/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BotsRouteImport } from './routes/bots'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BotsNewRouteImport } from './routes/bots/new'
import { Route as BotsIdRouteImport } from './routes/bots/$id'
import { Route as LeadsRouteImport } from './routes/leads'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsRoute = BotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsNewRoute = BotsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BotsRoute,
} as any)
const BotsIdRoute = BotsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BotsRoute,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bots': typeof BotsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/bots/$id': typeof BotsIdRoute
  '/bots/new': typeof BotsNewRoute
  '/leads': typeof LeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bots': typeof BotsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/bots/$id': typeof BotsIdRoute
  '/bots/new': typeof BotsNewRoute
  '/leads': typeof LeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bots': typeof BotsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/bots/$id': typeof BotsIdRoute
  '/bots/new': typeof BotsNewRoute
  '/leads': typeof LeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bots'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/bots/$id'
    | '/bots/new'
    | '/leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bots'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/bots/$id'
    | '/bots/new'
    | '/leads'
  id:
    | '__root__'
    | '/'
    | '/bots'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/bots/$id'
    | '/bots/new'
  fileRoutesById: FileRoutesById
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots': {
      id: '/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof BotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/new': {
      id: '/bots/new'
      path: '/new'
      fullPath: '/bots/new'
      preLoaderRoute: typeof BotsNewRouteImport
      parentRoute: typeof BotsRoute
    }
    '/bots/$id': {
      id: '/bots/$id'
      path: '/$id'
      fullPath: '/bots/$id'
      preLoaderRoute: typeof BotsIdRouteImport
      parentRoute: typeof BotsRoute
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BotsRouteChildren {
  BotsIdRoute: typeof BotsIdRoute
  BotsNewRoute: typeof BotsNewRoute
}

const BotsRouteChildren: BotsRouteChildren = {
  BotsIdRoute: BotsIdRoute,
  BotsNewRoute: BotsNewRoute,
}

const BotsRouteWithChildren = BotsRoute._addFileChildren(BotsRouteChildren)

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BotsRoute: typeof BotsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  LeadsRoute: typeof LeadsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BotsRoute: BotsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  LeadsRoute: LeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
